apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: nginx:1.21.1
          ports:
            - containerPort: 80
